// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using SP20.P05.Web.Data;

namespace SP20.P05.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200212144019_Phase3Domain")]
    partial class Phase3Domain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SP20.P04.Web.Features.FarmFieldTickets.FarmFieldTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FarmFieldId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Redeemed")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TicketTimeSlot")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FarmFieldId");

                    b.ToTable("FarmFieldTickets");
                });

            modelBuilder.Entity("SP20.P04.Web.Features.FarmFields.FarmField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FarmFields");
                });

            modelBuilder.Entity("SP20.P04.Web.Features.FarmFieldTickets.FarmFieldTicket", b =>
                {
                    b.HasOne("SP20.P04.Web.Features.FarmFields.FarmField", "FarmField")
                        .WithMany("Tickets")
                        .HasForeignKey("FarmFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SP20.P04.Web.Features.FarmFields.FarmField", b =>
                {
                    b.OwnsOne("SP20.P04.Web.Features.Shared.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<int>("FarmFieldId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("Height")
                                .HasColumnType("int");

                            b1.Property<int>("Width")
                                .HasColumnType("int");

                            b1.HasKey("FarmFieldId");

                            b1.ToTable("FarmFields");

                            b1.WithOwner()
                                .HasForeignKey("FarmFieldId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
